<?xml version="1.0" ?>
<definitions name="asignaturaService"
    xmlns = "http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap = "http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:tns = "http://localhost:8080/asignatura.wsdl"
    xmlns:xsd = "http://www.w3.org/2001/XMLSchema">

    <message name = "asignaturaRequest">
        <part name = "testParam" type = "xsd:string"/>
    </message>
    <message name = "asignaturaResponse">
        <part name = "status" type = "xsd:string"/>
    </message>

    <portType name = "asignaturaPortType">
        <operation name = "getAsignaturas">
            <input message = "tns:asignaturaRequest"/>
            <output message = "tns:asignaturaResponse"/>
        </operation>
    </portType>

    <binding name = "asignaturaBinding" type = "tns:asignaturaPortType">
        <soap:binding style = "rpc"
            transport = "http://schemas.xmlsoap.org/soap/http"/>
        <operation name = "getAsignaturas">
            <soap:operation soapAction = "getAsignaturas"/>
            <input>
                <soap:body encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"  namespace = "urn:examples:MyService" use = "encoded"/>
            </input>
            <output>
                <soap:body encodingStyle = "http://schemas.xmlsoap.org/soap/encoding/"  namespace = "urn:examples:MyService" use = "encoded"/>
            </output>
        </operation>
    </binding>

    <service name="asignaturaService">
        <documentation> servicio expuesto al equipo 1D y consume del 1C.
        </documentation>
        <port binding="asignaturaBinding" name="asignaturaPortType">
            <soap:address location="http://localhost:8080/asignaturas"/>
        </port>
    </service>

</definitions>
